### ISSUE TITLE
Issue with test data alignments

### ISSUE THREAD

**Issue by mmarszalkowski** [lucanest/Phyloformer#7]
The conda method for installation doesn't seem to work and I ran into the same error messages as a previous issue post, but the pip install method worked fine. However, I am unable to run python testdata/test.py

Traceback (most recent call last):
  File "/home/mikolaj/Phyloformer/testdata/test.py", line 14, in <module>
    t2=Tree(os.path.join(preds,tree.split('.nwk')[0]+'.pf.nwk'))
  File "/home/mikolaj/anaconda3/lib/python3.9/site-packages/ete3/coretype/tree.py", line 212, in __init__
    read_newick(newick, root_node = self, format=format,
  File "/home/mikolaj/anaconda3/lib/python3.9/site-packages/ete3/parser/newick.py", line 264, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
ete3.parser.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
You may want to check other newick loading flags like 'format' or 'quoted_node_names'.

I think there might be an issue converting the alignments trees into the correct .pf.nwk format. Do you have any suggestions?

**Comment by lucblassel** [comment]
Hello @1mikolajm, thanks for bringing this to our attention. There was a slight mismatch between the README and the underlying python scripts.  

The README has been updated in #8 so if you follow the new installation and testing instructions all should work as advertised. 

## Install the package:
```bash
# Install mamba if you want to use it instead of conda
conda install -n base -c conda-forge mamba

# Clone the phyloformer repo
git clone https://github.com/lucanest/Phyloformer.git && cd Phyloformer

# Create the virtual env and install the phyloformer package inside
conda create -n phylo python=3.9
conda activate phylo
pip install .
```

## Test the package
```bash
# Make predictions
predict testdata/alignments

# Evaluate predictions
evaluate --true testdata/trees --predictions testdata/alignments
```

I hope this solves your issue.

**Comment by LIPENGJUN2022** [comment]
problem when i use this command: python infer_alns.py   --trees   --outdir data/testdata/pf_tree   models/pf.ckpt   data/testdata/msas
/home/lpengjun/Desktop/Phyloformer/infer_alns.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(args.weights, map_location=device)
  0%|                                             | 0/14723 [00:00<?, ?it/s]/home/lpengjun/miniconda3/envs/phylo/lib/python3.9/site-packages/skbio/util/_warning.py:40: DeprecationWarning: `nj` has been deprecated since 0.6.3. `result_constructor` is deprecated and will be removed in a future release.
  warn(message, warning)
  0%|                                             | 0/14723 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lpengjun/Desktop/Phyloformer/infer_alns.py", line 122, in <module>
    outfile.write(nj(dm, result_constructor=str))
  File "/home/lpengjun/miniconda3/envs/phylo/lib/python3.9/site-packages/skbio/util/_decorator.py", line 262, in wrapper
    return func(*args, **kwargs)
  File "/home/lpengjun/miniconda3/envs/phylo/lib/python3.9/site-packages/skbio/tree/_nj.py", line 151, in nj
    lm = _nj(dm_)
  File "/home/lpengjun/miniconda3/envs/phylo/lib/python3.9/site-packages/skbio/tree/_nj.py", line 204, in _nj
    i, j = nj_minq_cy(dm_, sums_)
  File "skbio/tree/_c_nj.pyx", line 15, in skbio.tree._c_nj.nj_minq_cy
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'

**Comment by lucanest** [comment]
Hello @LIPENGJUN2022 , thanks for bringing this to our attention. There's seems to be a change in skbio's nj function which now requires the datatype of the distance matrix to be a double. The code in infer_alns.py has been modified to accommodate this. This should solve the issue.
